---
abstract: 'A simple-to-use XML module, for parsing and creating XML documents'
author:
  - 'Alexander Karelas <karjala@cpan.org>'
build_requires:
  File::Temp: 0
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-MyXML
requires:
  Carp: 0
  Encode: 0
  Exporter: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/akarelas/xml-myxml/issues
  homepage: https://github.com/akarelas/xml-myxml
  repository: https://github.com/akarelas/xml-myxml.git
version: 0.0992
